apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: Vipul
spec:
  type: website
  lifecycle: experimental
  owner: Vipul
  system: frontend
  providesApis: [example-grpc-api]
  consumesApis: 
    - default/backend-api
  dependsOn: 
    - resource: frontend-database
    - component: backend-api
    - service: logging-service
