apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: Vipul
spec:
  type: website
  lifecycle: experimental
  owner: Vipul
  system: frontend-system
  providesApis: 
    -default/react-app-api
  consumesApis:
    -default/backend-api
  
